smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: '<username>'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true
  
public_host: 'public.domain.com'

ftps:
  address: 'ftp.com'
  user: 'user'
  password: 'password'

zip:
  filename: 'data.zip'
  password: 'data'
