smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: '<username>'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true
  
public_host: 'public.domain.com'

ftps:
  address: 'ftp.com'
  port: 990
  user: 'user'
  password: 'password'

zip:
  path: '/folder'
  filename: 'data.zip'
  password: 'data'

table_maps:
  origin_tablename: 'dest_tablename'

field_maps_tablename:
  key: 'field_id'
  many_to_one_association: 
    ['column1', 'column2']: 'dest_column'
  many_to_one_association_key:
    dest_column: 'field_id'       
