common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'libreunir' %>
  password: <%= ENV['TRAVIS'] ? '' : 'libreunir' %>

development:
  database: libreunir_development
  <<: *common

test:
  database: libreunir_test
  <<: *common

production:
  database: libreunir_production
  <<: *common

sandbox:
  database: libreunir_production
  <<: *common
